### ISSUE TITLE
Image files are converted when the destination type is a video format

### ISSUE THREAD

**Issue by FinalStaticFox** [nschlia/ffmpegfs#28]
There seems to be a regression from #11 : if the --desttype option is not an audio only format (ie: Opus, MP3, WAV, AIFF), all image files are converted.

It happens on the latest release (1.7) and the latest master, both built on Fedora 29.

**Comment by nschlia** [comment]
I will check that. Thanks for notifying me.

**Comment by nschlia** [comment]
Seems that the FFmpeg API function I was using tagged BMP or JPG as MJPEG video, I have refined the detection. Works for the images I tried it on.

**Comment by nschlia** [comment]
Fix works with official FFmpeg releases. With somewhat recent daily builds it fails, because av_guess_codec/av_guess_format actually seem to report the real codecs for that file. The offical version checks the file extension only - e.g flac returns AV_CODEC_ID_NONE. Latest build versions return PNG or JPG if the audio file has a album art embedded in it. Nice, but breaks this fix.

Reopened, will implemenet a solution for any API version.

**Comment by nschlia** [comment]
OK, changed the code to use a fixed list instead of FFmpeg API functions subject to change in the future.
